In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('House_Price_data.csv')

In [3]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [4]:
df.shape

(4600, 18)

In [5]:
df.dtypes

date                 str
price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street               str
city                 str
statezip             str
country              str
dtype: object

In [6]:
df.isna().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [7]:
data = df.copy()

In [8]:
data['date'] = pd.to_datetime(data['date'])

In [9]:
data.describe()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4600,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,2014-06-07 03:14:42.782608,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
min,2014-05-02 00:00:00,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,2014-05-21 00:00:00,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,2014-06-09 00:00:00,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,2014-06-24 00:00:00,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2014-07-10 00:00:00,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000
std,NaN,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536

In [10]:
data['Sale_month'] = data['date'].dt.month

In [11]:
data['Sale_year'] = data['date'].dt.year

In [12]:
data.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country,Sale_month,Sale_year
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA,5,2014
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA,5,2014
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA,5,2014
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA,5,2014
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA,5,2014

In [13]:
data = data.drop(columns = ['country', 'street', 'date'])

In [14]:
data.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city', 'statezip', 'Sale_month',
       'Sale_year'],
      dtype='str')

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = data.drop(columns = ['price']) #feature variables
y = data.price

In [17]:
y

0       3.130000e+05
1       2.384000e+06
2       3.420000e+05
3       4.200000e+05
4       5.500000e+05
            ...
4595    3.081667e+05
4596    5.343333e+05
4597    4.169042e+05
4598    2.034000e+05
4599    2.206000e+05
Name: price, Length: 4600, dtype: float64

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 1
)

In [19]:
X_train.shape

(3680, 16)

In [20]:
X_test.shape

(920, 16)

In [21]:
X_numerical = X.select_dtypes(include=np.number)
X_numerical.head()
X_categorical = X.select_dtypes(include='object')
X_categorical.head()
from sklearn.preprocessing import StandardScaler, MinMaxScaler
standard_scaled_X = StandardScaler().fit_transform(X_numerical)
minmax_scaled_X = MinMaxScaler().fit_transform(X_numerical)
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
one_hot_encoder = OneHotEncoder()
label_encoder = LabelEncoder()
city_ohe = one_hot_encoder.fit_transform(X_categorical[['city']]).toarray()
city_ohe_df = pd.DataFrame(city_ohe, columns=one_hot_encoder.get_feature_names_out(['city']))
example_labels = label_encoder.fit_transform(["low", "high", "medium", "high"])
temp = pd.DataFrame({"city": ["A", "A", "B", "B"], "price": [100, 200, 300, 500]})
city_mean = temp.groupby("city")["price"].mean()
temp["city_target_encoded"] = temp["city"].map(city_mean)
display(temp)
X.shape[1]
from sklearn.feature_selection import SelectKBest, f_regression
selector = SelectKBest(score_func=f_regression, k=min(5, X_numerical.shape[1]))
selector.fit(X_numerical,y)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
X_train_num, X_test_num, y_train_num, y_test = train_test_split(X_numerical, y, test_size=0.2,random_state=1)
model.fit(X_train_num, y_train)
model.intercept_
model.coef_[0]
y_pred = model.predict(X_test_num)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test,y_pred)
mae
mse = mean_squared_error(y_test, y_pred)
mse
rmse = np.sqrt(mse)
rmse
r2 = r2_score(y_test,y_pred)
r2

C:\Users\aamir\AppData\Local\Temp\ipykernel_20460\146162677.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X_categorical = X.select_dtypes(include='object')

  city  price  city_target_encoded
0    A    100                150.0
1    A    200                150.0
2    B    300                400.0
3    B    500                400.0

0.46047131029990807

In [22]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler

In [23]:
X_numerical = X.select_dtypes(include = np.number)

In [24]:
X_categorical = X.select_dtypes(include = 'object')

C:\Users\aamir\AppData\Local\Temp\ipykernel_20460\2069332220.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X_categorical = X.select_dtypes(include = 'object')

In [25]:
X_num_std_scaled = StandardScaler().fit_transform(X_numerical)

In [26]:
X_numerical

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,Sale_month,Sale_year
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,5,2014
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,5,2014
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,5,2014
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,5,2014
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,5,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,7,2014
4596,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,7,2014
4597,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,7,2014
4598,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,7,2014
4599,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,7,2014

In [27]:
X_num_std_scaled

array([[-0.44112227, -0.84320364, -0.82997105, ...,  1.22167046,
        -1.10797649,  0.        ],
       [ 1.75970468,  0.43280154,  1.56852826, ..., -0.82569345,
        -1.10797649,  0.        ],
       [-0.44112227, -0.20520105, -0.21736733, ..., -0.82569345,
        -1.10797649,  0.        ],
       ...,
       [-0.44112227,  0.43280154,  0.90400897, ..., -0.82569345,
         1.81695428,  0.        ],
       [ 0.6592912 , -0.20520105, -0.05123751, ..., -0.82569345,
         1.81695428,  0.        ],
       [-0.44112227,  0.43280154, -0.67422434, ..., -0.82569345,
         1.81695428,  0.        ]], shape=(4600, 14))

In [28]:
X_num_robust_scaled = RobustScaler().fit_transform(X_numerical)

In [29]:
X_num_robust_scaled

array([[ 0.        , -1.        , -0.55172414, ...,  1.0030015 ,
        -1.        ,  0.        ],
       [ 2.        ,  0.33333333,  1.43965517, ...,  0.        ,
        -1.        ,  0.        ],
       [ 0.        , -0.33333333, -0.04310345, ...,  0.        ,
        -1.        ,  0.        ],
       ...,
       [ 0.        ,  0.33333333,  0.88793103, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.        , -0.33333333,  0.09482759, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        ,  0.33333333, -0.42241379, ...,  0.        ,
         1.        ,  0.        ]], shape=(4600, 14))

In [30]:
X_num_minmax_scaled = MinMaxScaler().fit_transform(X_numerical)

In [31]:
X_num_minmax_scaled

array([[0.33333333, 0.1875    , 0.07365224, ..., 0.99553128, 0.        ,
        0.        ],
       [0.55555556, 0.3125    , 0.24905087, ..., 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.25      , 0.11845103, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.33333333, 0.3125    , 0.20045558, ..., 0.        , 1.        ,
        0.        ],
       [0.44444444, 0.25      , 0.13059985, ..., 0.        , 1.        ,
        0.        ],
       [0.33333333, 0.3125    , 0.08504176, ..., 0.        , 1.        ,
        0.        ]], shape=(4600, 14))

In [32]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [33]:
X_categorical

           city  statezip
0     Shoreline  WA 98133
1       Seattle  WA 98119
2          Kent  WA 98042
3      Bellevue  WA 98008
4       Redmond  WA 98052
...         ...       ...
4595    Seattle  WA 98133
4596   Bellevue  WA 98007
4597     Renton  WA 98059
4598    Seattle  WA 98178
4599  Covington  WA 98042

[4600 rows x 2 columns]

In [34]:
ohe = OneHotEncoder()

In [35]:
city_ohe = ohe.fit_transform(X_categorical[['city']]).toarray()

In [36]:
city_ohe

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(4600, 44))

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
model = LinearRegression()

In [39]:
X_train_num, X_test_num, y_train, y_test = train_test_split(
    X_numerical, 
    y,
    test_size = 0.2,
    random_state = 1
)

In [40]:
model.fit(X_train_num, y_train)

LinearRegression()

In [41]:
y_pred = model.predict(X_test_num)

In [52]:
y_test[1]

np.float64(2384000.0)

In [51]:
y_pred[1]

np.float64(708429.4340995019)

In [43]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [44]:
mse = mean_squared_error(y_pred, y_test)
mse

65796813530.49219

In [45]:
rmse = np.sqrt(mse)
rmse

np.float64(256508.89561668652)

In [46]:
mae = mean_absolute_error(y_pred, y_test)
mae

164372.35441128226

In [47]:
r2 = r2_score(y_pred, y_test)
r2

-0.030865862913731723

In [48]:
label_encoded_city = LabelEncoder().fit_transform(X_categorical[['city']])

c:\Users\aamir\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [49]:
label_encoded_city

array([36, 35, 18, ..., 32, 35,  9], shape=(4600,))