In [2]:
import numpy as np

In [3]:
A = np.array([
    [3,4,5],
    [5,6,7],
    [9,8,5]
])

B = np.array([
    [9,8,7],
    [6,6,4],
    [3,2,1]
])

In [7]:
A * B

array([[27, 32, 35],
       [30, 36, 28],
       [27, 16,  5]])

In [8]:
A @ B

array([[ 66,  58,  42],
       [102,  90,  66],
       [144, 130, 100]])

In [10]:
A.shape

(3, 3)

In [11]:
A.ndim

2

In [12]:
A.size

9

In [13]:
A.T

array([[3, 5, 9],
       [4, 6, 8],
       [5, 7, 5]])

In [14]:
A

array([[3, 4, 5],
       [5, 6, 7],
       [9, 8, 5]])

In [15]:
np.linalg.det(A)

np.float64(4.0000000000000115)

In [16]:
det(A)

NameError: name 'det' is not defined

In [18]:
A/B

array([[0.33333333, 0.5       , 0.71428571],
       [0.83333333, 1.        , 1.75      ],
       [3.        , 4.        , 5.        ]])

In [19]:
np.linalg.inv(A)

array([[-6.5,  5. , -0.5],
       [ 9.5, -7.5,  1. ],
       [-3.5,  3. , -0.5]])

In [23]:
eigen_values, eigen_vectors = np.linalg.eig(A)

In [24]:
eigen_values

array([17.35521503+0.j, -0.07015963+0.j, -3.2850554 +0.j])

In [25]:
eigen_vectors

array([[-0.40700984+0.j, -0.52966831+0.j, -0.39539023+0.j],
       [-0.60246056+0.j,  0.79060123+0.j, -0.40762431+0.j],
       [-0.68657429+0.j, -0.30724773+0.j,  0.82310934+0.j]])

In [26]:
A_eq = np.array([
    [2,1],
    [4,5]
])

b = np.array([9,16])

In [27]:
np.linalg.solve(A_eq,b)

array([ 4.83333333, -0.66666667])

In [29]:
import seaborn as sns

In [31]:
df = sns.load_dataset('tips')

In [32]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [37]:
df.describe().T

            count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [38]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [43]:
max(df['tip']) - min(df['tip'])

9.0

In [44]:
bill = df['total_bill']

In [45]:
bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [46]:
bill.quantile(0.5)

np.float64(17.795)

In [51]:
np.percentile(bill, 95.6)

np.float64(38.942519999999995)

In [52]:
bill.skew()

np.float64(1.1332130376158205)

In [53]:
bill.kurt()

np.float64(1.2184840156638854)

In [55]:
df.to_csv('tips_data.csv')

In [58]:
import pandas as pd
pd.read_csv('tips_data.csv')

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [59]:
bill = df['total_bill']

In [65]:
high_bill = df[df['total_bill'] > 30]

In [67]:
high_bill.shape

(32, 7)

In [71]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [85]:
df[(df['sex'] == 'Female') | (df['smoker'] == 'Yes')]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[147 rows x 7 columns]

In [87]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64