In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = sns.load_dataset('titanic')

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df.shape

(891, 15)

In [6]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [7]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
features = ['pclass','sex','age','sibsp','parch','fare','embarked']

In [9]:
X = df[features]
y = df.survived

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 1
)

In [12]:
X_train.shape

(712, 7)

In [13]:
X_test.shape

(179, 7)

In [14]:
X.head()

   pclass     sex   age  sibsp  parch     fare embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [15]:
numeric_features = ['pclass',"age","sibsp",'parch','fare']
categorical_features = ['sex','embarked']

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [17]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy= 'median')),
    ("scaler", StandardScaler())
])

In [18]:
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy= 'most_frequent')),
    ("onehot", OneHotEncoder())
])

In [19]:
preproccessor = ColumnTransformer([
    ('num', numeric_pipeline,numeric_features),
    ('cat',categorical_pipeline, categorical_features)
])

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [21]:
# Logistic regression
logistic_model = Pipeline([
    ('preproccessor', preproccessor),
    ('model', LogisticRegression(max_iter=100))
])

In [22]:
logistic_model.fit(X_train,y_train)

Pipeline(steps=[('preproccessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['pclass', 'age', 'sibsp',
                                                   'parch', 'fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['sex', 'embarked'])])),
                ('model', LogisticRegression())])

In [23]:
y_pred_lr = logistic_model.predict(X_test)
y_prob_lr = logistic_model.predict_proba(X_test)

In [24]:
# decision tree
tree_model = Pipeline([
    ('preproccessor', preproccessor),
    ('model', DecisionTreeClassifier(max_depth=4))
])

In [25]:
tree_model.fit(X_train,y_train)

Pipeline(steps=[('preproccessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['pclass', 'age', 'sibsp',
                                                   'parch', 'fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['sex', 'embarked'])])),
                ('model', DecisionTreeClassifier(max_depth=4))])

In [26]:
y_pred_tree = tree_model.predict(X_test)
y_prob_tree = tree_model.predict_proba(X_test)

In [28]:
rf_model = Pipeline([
    ('preprocessor', preproccessor),
    ('model', RandomForestClassifier(n_estimators=100))
])

In [ ]:
# random forest
rf_model = Pipeline([
    ('preproccessor', preproccessor),
    ('model', RandomForestClassifier(n_estimators=100))
])

In [29]:
rf_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['pclass', 'age', 'sibsp',
                                                   'parch', 'fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['sex', 'embarked'])])),
                ('model', RandomForestClassifier())])

In [ ]:
rf_model.fit(X_train,y_train)

Pipeline(steps=[('preproccessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['pclass', 'age', 'sibsp',
                                                   'parch', 'fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['sex', 'embarked'])])),
                ('model', RandomForestClassifier())])

In [30]:
y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)

In [31]:
#support vector machine
svm_model = Pipeline([
    ('preproccessor', preproccessor),
    ('model', SVC(kernel = 'rbf', C=1.0,probability=True))
])

In [32]:
svm_model.fit(X_train,y_train)

c:\Users\aamir\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

Pipeline(steps=[('preproccessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['pclass', 'age', 'sibsp',
                                                   'parch', 'fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['sex', 'embarked'])])),
                ('model', SVC(probability=True))])

In [33]:
y_pred_svm = svm_model.predict(X_test)
y_prob_svm = svm_model.predict_proba(X_test)

In [34]:
knn_model = Pipeline([
    ('preproccessor', preproccessor),
    ('model', KNeighborsClassifier(n_neighbors=5))
])

In [35]:
knn_model.fit(X_train, y_train)

Pipeline(steps=[('preproccessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['pclass', 'age', 'sibsp',
                                                   'parch', 'fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['sex', 'embarked'])])),
                ('model', KNeighborsClassifier())])

In [36]:
y_pred_knn = knn_model.predict(X_test)
y_prob_knn = knn_model.predict_proba(X_test)

In [ ]:
from sklearn.metrics import (accuracy_score,precision_score, recall_score,
                             f1_score,roc_auc_score, confusion_matrix,
                             classification_report,ConfusionMatrixDisplay)

In [ ]:
len(y_pred_lr)

179

In [ ]:
def evaluate_model(name,y_true, y_pred, y_prob):
    return {
        "Model": name,
        "Accuracy": accuracy_score(y_true,y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred),
        "ROC-AUC": roc_auc_score(y_true,y_pred)
    }
results = [
    evaluate_model("Logistic Regression", y_test, y_pred_lr, y_prob_lr),
    evaluate_model("Decision tree", y_test, y_pred_tree, y_prob_tree),
    evaluate_model("Random Forest", y_test, y_pred_rf, y_prob_rf),
    evaluate_model("Support Vector Machine", y_test, y_pred_svm, y_prob_svm),
    evaluate_model("K Nearest Neighbour", y_test, y_pred_knn, y_prob_knn),
]

In [ ]:
results_df = pd.DataFrame(results)

In [ ]:
results_df

                        Accuracy  Precision    Recall        F1   ROC-AUC
Model
Logistic Regression     0.798883   0.760563  0.739726  0.750000  0.789674
Decision tree           0.804469   0.816667  0.671233  0.736842  0.783730
Random Forest           0.776536   0.789474  0.616438  0.692308  0.751615
Support Vector Machine  0.787709   0.818182  0.616438  0.703125  0.761049
K Nearest Neighbour     0.759777   0.777778  0.575342  0.661417  0.731067

In [ ]:
results_df.columns
results_df.head()

                        Accuracy  Precision    Recall        F1   ROC-AUC
Model
Logistic Regression     0.798883   0.760563  0.739726  0.750000  0.789674
Decision tree           0.804469   0.816667  0.671233  0.736842  0.783730
Random Forest           0.776536   0.789474  0.616438  0.692308  0.751615
Support Vector Machine  0.787709   0.818182  0.616438  0.703125  0.761049
K Nearest Neighbour     0.759777   0.777778  0.575342  0.661417  0.731067